### ISSUE TITLE
Desync of game state on PredictionBarrierReached

### ISSUE THREAD

**Issue by ValorZard** [HouraiTeahouse/backroll-rs#12]
Whenever the prediction barrier gets reached due to an influx of inputs, there will be a bunch of jitters, which leads to the players' positions in [this sample project](https://github.com/ValorZard/simple-backroll) getting desynced. The current theory is that the inputs during that frame don't get read.

**Comment by james7132** [comment]
This should be fixed as of cf0b896c7e56c7916aceb8595fd4cdb04df44ea8.
