### ISSUE TITLE
Naming Conventions: "Backroll" prefix redundant?

### ISSUE THREAD

**Issue by 0----0** [HouraiTeahouse/backroll-rs#7]
The library currently has a number of typenames prefixed with "Backroll," which seems to add a lot of name bloat.  The examples seem to deal with this name bloat with `use backroll::*;`.  Rather than typing something like 
```rust
use backroll::*;
// ...
    let local_handle: BackrollPlayerHandle = session_builder.add_player(BackrollPlayer::Local);
```
would it be more idiomatic to leave the namespace intact and use
```rust
    let local_handle: backroll::PlayerHandle = session_builderr.add_player(backroll::Player::Local);
```
to avoid conflicts?

I'm not super familiar with Rust naming conventions, so consider this a suggestion, but it seems like this is the convention among other Rust libraries, with names like `Context`, `Sprite`, etc going un-prefixed.

**Comment by james7132** [comment]
This is a bit of a holdover from the direct GGPO port where C doesn't exactly have namespaces/modules. Should be a pretty simple global `%s/Backroll//g` if anyone wants to tackle this.

**Comment by seanchen1991** [comment]
I'd like to claim this 🙂

**Comment by seanchen1991** [comment]
So it looks like there's a `BackrollConfig` in `backroll/lib.rs`, as well as a `Config` in `backroll/sync.rs`. I'm thinking that `BackrollConfig` should be renamed to `Config` and then changing the name of `Config` in `sync.rs` to something like `PlayerConfig`. Does that sound reasonable?

**Comment by james7132** [comment]
For disambiguation, yes, that definitely should be renamed.
